Repository vedantmgoyal9/winget-releaser, pull requests merged in 2022-11, with the labels that each got.

#53 docs: update `version` config example
  README.md
Labels: documentation, enhancement

#41 Migrate to Typescript + Update YamlCreate
  .all-contributorsrc
  .github/workflows/codeql-analysis.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE.md
  README.md
  dist/index.js
  package-lock.json
  package.json
  src/YamlCreate.ps1
  src/main.ts
  tsconfig.json
Labels: enhancement, feat, dependencies

#60 Update .gitignore with NodeJS files
  .gitignore
  dist/index.js
  dist/licenses.txt
Labels: enhancement

#54 docs: added notes about the usage of the action
  README.md
Labels: documentation
